# Generated by Django 2.2.1 on 2019-05-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(max_length=255)),
                ('choice_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_question', models.CharField(max_length=255)),
                ('poll_creator', models.CharField(max_length=255)),
                ('poll_created', models.DateTimeField(auto_now=True)),
                ('poll_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Choice')),
            ],
        ),
    ]
