# Generated by Django 2.2.1 on 2019-05-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('emp_status', models.CharField(choices=[('EMP', 'Currently Employed'), ('UNE', 'Currently Unemployed'), ('RET', 'Retired from working'), ('STU', 'I am a student')], default='STU', max_length=2)),
                ('age', models.DateField()),
            ],
        ),
    ]
