# Generated by Django 2.2.1 on 2019-05-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='emp_status',
            field=models.CharField(choices=[('EMP', 'Currently Employed'), ('UNE', 'Currently Unemployed'), ('RET', 'Retired from working'), ('STU', 'I am a student')], default='STU', max_length=3),
        ),
    ]
