# Generated by Django 2.2.1 on 2019-05-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20190522_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='employment',
            name='suburb',
            field=models.ManyToManyField(to='poll.Suburb'),
        ),
    ]
